services:
  task.services.pusher:
    class: TaskBundle\Services\Pusher
    arguments:
      - '@doctrine.orm.entity_manager'

  task.services.locker:
    class: TaskBundle\Services\Locker
    public: false
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@task.services.repository'

  task.services.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
        - TaskBundle:Task
